// src/app/affiliates/[partners]/partnerComponents/stats.js

import React from "react";

export default function Stats({ data }) {
  // Log the received data to ensure it's being passed correctly
  console.log("Affiliate data received in Stats component:", data);

  // If no data is passed, show a loading or error message
  if (!data) {
    return <p className="font-overpass text-white">Loading...</p>;
  }

  // Extract data from the props
  const { numberOfReferrals, totalReferredBalance, referredUsers } = data;

  // Calculate total earnings and amount due
  const totalEarnings = totalReferredBalance * 0.5; // Assume 50% earnings for demonstration
  const amountDue = totalEarnings / 2; // Just for demonstration

  // Utility function to format ETH values to 6 decimal places
  const formatEthValue = (value) => parseFloat(value).toFixed(6);

  return (
    <div className="w-full min-h-screen bg-gray-900 flex flex-col items-center justify-center p-6 space-y-8">
      {/* Header */}
      <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-yellow-300 mb-8 text-center font-overpass">
        Your Affiliate Stats
      </h1>

      {/* Stats Container */}
      <div className="bg-gray-800 rounded-lg shadow-lg p-8 w-full max-w-4xl space-y-6 text-white font-overpass">
        {/* Earnings Overview */}
        <div className="flex flex-col md:flex-row md:justify-between md:space-x-8 space-y-6 md:space-y-0">
          {/* Total Referrals */}
          <div className="flex flex-col items-center justify-center bg-gray-700 p-6 rounded-lg shadow-md w-full md:w-1/3">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-semibold text-pink-400 font-overpass">
              Total Referrals
            </h2>
            <p className="text-3xl md:text-4xl lg:text-5xl font-bold mt-4 font-overpass">
              {numberOfReferrals}
            </p>
            <p className="text-xs md:text-sm text-gray-400 mt-2 font-overpass">
              Users who joined through your link.
            </p>
          </div>

          {/* Total Earnings */}
          <div className="flex flex-col items-center justify-center bg-gray-700 p-6 rounded-lg shadow-md w-full md:w-1/3">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-semibold text-green-400 font-overpass">
              Total Earnings
            </h2>
            <p className="text-3xl md:text-4xl lg:text-5xl font-bold mt-4 font-overpass">
              {formatEthValue(totalEarnings)} ETH
            </p>
            <p className="text-xs md:text-sm text-gray-400 mt-2 font-overpass">
              Total amount earned from referrals.
            </p>
          </div>

          {/* Amount Due */}
          <div className="flex flex-col items-center justify-center bg-gray-700 p-6 rounded-lg shadow-md w-full md:w-1/3">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-semibold text-yellow-300 font-overpass">
              Amount Due
            </h2>
            <p className="text-3xl md:text-4xl lg:text-5xl font-bold mt-4 font-overpass">
              {formatEthValue(amountDue)} ETH
            </p>
            <p className="text-xs md:text-sm text-gray-400 mt-2 font-overpass">
              Payout pending to your wallet.
            </p>
          </div>
        </div>

        {/* Additional Info */}
        <div className="flex flex-col md:flex-row md:justify-between space-y-6 md:space-y-0 md:space-x-8">
          {/* Total Referral Losses */}
          <div className="flex flex-col items-center justify-center bg-gray-700 p-6 rounded-lg shadow-md w-full">
            <h2 className="text-xl md:text-2xl lg:text-3xl font-semibold text-red-400 font-overpass">
              Total Referral Losses
            </h2>
            <p className="text-3xl md:text-4xl lg:text-5xl font-bold mt-4 font-overpass">
              {formatEthValue(totalReferredBalance - totalEarnings)} ETH
            </p>
            <p className="text-xs md:text-sm text-gray-400 mt-2 font-overpass">
              Total losses generated by your referrals.
            </p>
          </div>

          {/* Earnings Percentage */}
          <div className="flex flex-col items-center justify-center bg-gray-700 p-6 rounded-lg shadow-md w-full">
            <h2 className="text-xl md:text-2xl lg:text-3xl font-semibold text-indigo-400 font-overpass">
              Your Earnings Percentage
            </h2>
            <p className="text-3xl md:text-4xl lg:text-5xl font-bold mt-4 font-overpass">
              50%
            </p>
            <p className="text-xs md:text-sm text-gray-400 mt-2 font-overpass">
              Share of the total referral profits.
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-4 justify-center mt-8">
          <div
            className="w-full md:w-auto text-sm text-center font-semibold font-overpass hover:bg-green-600 text-white rounded-lg shadow"
          >
            We pay you out & reset the counter every Friday <br />
            If we dont reset the counter it means we havent paid you out yet.
          </div>
        </div>
      </div>
    </div>
  );
}
